# https://docs.microsoft.com/azure/devops/pipelines/ecosystems/android
pool:
  vmImage: 'ubuntu-latest'

variables:
- group: Haifa3dKeystoreSecrets
- name: DroidDir
  value: '$(System.DefaultWorkingDirectory)/src/android/Haifa3d'
- name: releaseFileName
  value: 'aab/release/app-release.aab'

stages:
- stage: Build
  jobs:
  - job: NBGV
    steps:
    - task: DotNetCoreCLI@2
      inputs:
        command: custom
        custom: tool
        arguments: install --tool-path . nbgv
      displayName: Install NBGV tool
    - script: ./nbgv cloud -c -a
      displayName: Set Version

  - job: BuildDebugAPK
    displayName: Build Debug APK
    dependsOn:
      - NBGV
    steps:
    - script: |
        export BUILD_ANDROIDVERSIONCODE=`git rev-list --count HEAD`
        echo "##vso[task.setvariable variable=BUILD_ANDROIDVERSIONCODE]$BUILD_ANDROIDVERSIONCODE"
        echo "Android VersionCode will be $BUILD_ANDROIDVERSIONCODE"
    - task: Gradle@2
      displayName: assembleDebug
      inputs:
        workingDirectory: '$(DroidDir)'
        gradleWrapperFile: '$(DroidDir)/gradlew'
        gradleOptions: '-Xmx3072m'
        publishJUnitResults: false
        testResultsFiles: '**/TEST-*.xml'
        tasks: 'assembleDebug'
    - publish: $(DroidDir)/app/build/outputs/apk
      artifact: apk

  - job: BuildReleaseAAB
    displayName: Build Release AAB
    dependsOn:
      - NBGV
    steps:
    - script: |
        export BUILD_ANDROIDVERSIONCODE=`git rev-list --count HEAD`
        echo "##vso[task.setvariable variable=BUILD_ANDROIDVERSIONCODE]$BUILD_ANDROIDVERSIONCODE"
        echo "Android VersionCode will be $BUILD_ANDROIDVERSIONCODE"
    - task: Gradle@2
      displayName: bundleRelease
      inputs:
        workingDirectory: '$(DroidDir)'
        gradleWrapperFile: '$(DroidDir)/gradlew'
        gradleOptions: '-Xmx3072m'
        publishJUnitResults: false
        testResultsFiles: '**/TEST-*.xml'
        tasks: 'bundleRelease'

    - publish: $(DroidDir)/app/build/outputs/bundle/
      artifact: aab

- stage: Deploy
  condition: and(succeeded(), startsWith(variables['build.sourceBranch'], 'refs/heads/release/'))
  jobs:
  - job: Sign
    displayName: Sign AAB
    steps:
    - checkout: none
    - task: DownloadPipelineArtifact@2
      inputs:
        source: 'current'
        patterns: '**/*.aab'
        path: '$(Pipeline.Workspace)/sign'
    - task: DownloadSecureFile@1
      name: haifa3dkeystore
      inputs:
        secureFile: 'haifa3d.jks'
    - script: 'jarsigner -verbose -sigalg SHA256withRSA -digestalg SHA-256 -storepass "$(keystorepsw)" -keypass "$(keypsw)"  -keystore $(haifa3dkeystore.secureFilePath) "$(Pipeline.Workspace)/sign/$(releaseFileName)" key0'
    - publish: $(Pipeline.Workspace)/sign/
      artifact: signed
  - job: GithubReleases
    dependsOn: Sign
    steps:
    - checkout: none
    - task: DownloadPipelineArtifact@2
      inputs:
        source: 'current' # Options: current, specific
        #project: # Required when source == Specific
        #pipeline: # Required when source == Specific
        #preferTriggeringPipeline: false # Optional
        #runVersion: 'latest' # Required when source == Specific# Options: latest, latestFromBranch, specific
        #runBranch: 'refs/heads/master' # Required when source == Specific && RunVersion == LatestFromBranch
        #runId: # Required when source == Specific && RunVersion == Specific
        #tags: # Optional
        #artifact: # Optional
        patterns: |
          **/*.apk
          **/signed/**/*.aab
        path: '$(Pipeline.Workspace)/githubrelease'
    - task: GitHubRelease@1
      inputs:
        gitHubConnection: georg-jung-oauth
        repositoryName: '$(Build.Repository.Name)' 
        action: 'create' # Options: create, edit, delete
        tagSource: userSpecifiedTag
        #tagPattern: # Optional
        tag: 'v$(Build.BuildNumber)' # Required when action == Edit || Action == Delete || TagSource == Manual
        #title: # Optional
        #releaseNotesSource: 'file' # Optional. Options: file, input
        #releaseNotesFile: # Optional
        #releaseNotes: # Optional
        assets: '$(Pipeline.Workspace)/githubrelease/**/*' # Optional
        #assetUploadMode: 'delete' # Optional. Options: delete, replace
        isDraft: true # Optional
        #isPreRelease: false # Optional
        addChangeLog: true # Optional
        #releaseTag: # Required when compareWith == LastReleaseByTag